### ISSUE TITLE
Lizenz?

### ISSUE THREAD

**Issue by willi84** [SupaplexOSM/strassenraumkarte-neukoelln#1]

**Comment by tordans** [comment]
Which part @willi84 

And yes, you are right, we need to add those.

**Comment by willi84** [comment]
a basic license for your project. e.g. in the route folder as LICENSE file

**Comment by tordans** [comment]
Thanks @willi84 for the nudge. You can find my take on described the licence of the different "parts" of this project at https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/blob/main/LICENSE.md. HTH
