### ISSUE TITLE
check if value is numeric

### ISSUE THREAD

**Issue by gislars** [SupaplexOSM/strassenraumkarte-neukoelln#12]
I had a problem with width values not beeing numeric. E.g. there are width values like "narrow" in OSM.

If you use a function like this 

```
def isfloat(num):
    try:
        float(num)
        return True
    except ValueError:
        return False
```

you can test if the value is numeric and if it is not, you can handle the case in an other way.

**Comment by SupaplexOSM** [comment]
Thanks! Just [updated](https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/commit/d56290b108b6a86b9364bd39ba9f4abb8c5efdc4) the script - it's using this check now. If there are non-numeric width values, it's using default values now.
