### ISSUE TITLE
Change images for parked cars

### ISSUE THREAD

**Issue by SupaplexOSM** [SupaplexOSM/strassenraumkarte-neukoelln#16]
Ich sollte bei Gelegenheit mal testen, ob die [schönen Fahrzeuge von Tobias Zwick](https://github.com/streetcomplete/StreetComplete/tree/master/res/graphics/lanes) gut in der Straßenraumkarte aussehen (unten im Bild).

![](https://user-images.githubusercontent.com/4661658/187932690-0fb5700f-bdd1-40c0-9543-7ea73bf0b4cb.png)

**Comment by tordans** [comment]
Wenn es soweit ist: Im Repo von Zlant hatte ich die Grafiken dafür aus dem StreetComplete repo schonmal recherchiert und gesammelt.

**Comment by SupaplexOSM** [comment]
> Wenn es soweit ist: Im Repo von Zlant hatte ich die Grafiken dafür aus dem StreetComplete repo schonmal recherchiert und gesammelt.

Sie verstecken sich auch hinter dem [Link](https://github.com/streetcomplete/StreetComplete/tree/master/res/graphics/lanes) oben - schöne svg's, sodass auch die Farben, Kontraste etc. angepasst werden können.

**Comment by SupaplexOSM** [comment]
Inzwischen habe ich bereits Versuche unternommen, diese Fahrzeuge zu nutzen, sie passen aber stilistisch und farblich nicht zur Straßenraumkarte. Den in der Straßenraumkarte verwendeten Modellen habe ich durch Licht/Schatten bereits etwas mehr "Räumlichkeit" verpasst, sodass es mMn eigentlich zur Zeit ganz gut passt.
