### ISSUE TITLE
Update Leaflet

### ISSUE THREAD

**Issue by SupaplexOSM** [SupaplexOSM/strassenraumkarte-neukoelln#18]
_Siehe auch https://github.com/osmberlin/parkraum.osm-verkehrswende.org/issues/36_

Je nach Browser/Betriebssystem scrollt die Karte mit dem Mausrad um zwei statt einer Zoomstufe. Mit einer neuen Leaflet-Version sollte das gefixt sein.

**Comment by tordans** [comment]
@SupaplexOSM ich habe gerade Leaflet und andere Dinge aktualisiert. Klick bitte nochmal rum, ob alles läuft.

Ich schließe hier schonmal; bitte ggf. wieder-öffnen.
