### ISSUE TITLE
Are translations planned?

### ISSUE THREAD

**Issue by le-jun** [SupaplexOSM/strassenraumkarte-neukoelln#19]
Your work is amazing! Unfortunately I don't speak German, do you plan to translate the UI to any other language? I understand that it's aimed at German speaking users first, but making the output comprehensible for others would make it easier to understand how the data can be used.

**Comment by tordans** [comment]
Unfortunately I don't see a manual translation system on the horizon.

I am, however, very open to improve the HTML in a way that makes it easier for Google Website Translations to work.

**Comment by tordans** [comment]
Are there specific parts that you would want to be translated? Maybe we can switch them to English ...

**Comment by le-jun** [comment]
Nothing specific I guess. Thanks anyway for your work, I'll stay tuned for your development.
