### ISSUE TITLE
Add Strassenraumkarte to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [SupaplexOSM/strassenraumkarte-neukoelln#21]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add Strassenraumkarte to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

**Comment by SupaplexOSM** [comment]
Straßenraumkarte is part of the Taginfo Project List since a while, so I will close this issue. Thanks for the hint.
