### ISSUE TITLE
Broken reference to manhole.svg

### ISSUE THREAD

**Issue by mikedld** [SupaplexOSM/strassenraumkarte-neukoelln#24]
The [mapstyle/strassenraumkarte.qgz](https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/blob/main/mapstyle/strassenraumkarte.qgz) project file references `@project_folder + '/symbols/man_made/manhole.svg'` (vector) image but there's no such file in the repository. Instead, [mapstyle/symbols/man_made/manhole.png](https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/blob/main/mapstyle/symbols/man_made/manhole.png) (non-vector) image exists.

Renders as questionmarks:
![imagen](https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/assets/298203/a97922a6-5033-4b40-ab2b-422f93102be5)

**Comment by SupaplexOSM** [comment]
Thanks @mikedld, forgot to replace the png after I updated this image/switched to svg some weeks ago!

P.S. The new [manhole.svg](https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/blob/main/mapstyle/symbols/man_made/manhole.svg) is somewhat provisional, but I wanted to use a graphic that makes a manhole more recognizable than before.
