### ISSUE TITLE
Diskussion about "Call for help from the data science community: Evaluate tradeoffs in data quality for mapping parking data in OSM"

### ISSUE THREAD

**Issue by tordans** [SupaplexOSM/strassenraumkarte-neukoelln#4]
Lets discuss questions, ideas and findings about https://supaplexosm.github.io/strassenraumkarte-neukoelln/posts/2021-12-13-evaluate-tradeoffs-in-data-quality-vs-mapping-details.html in this thread.

**Comment by mahbubur-87** [comment]
[Intermediate_Status_Report_28_12_2021.pdf](https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/files/7787774/Intermediate_Status_Report_28_12_2021.pdf)

Hello, I prepared a dataset for my urban technology course project work in the university. I prepared it from datasets from this github and datasets which were published in the last DSSG Berlin 2021.

The attached intermediate status report of my project work will give you an idea what I am doing at the moment. Also I attached the code for the data understanding and preparation.
   
[data_understanding_and_preparation (1).pdf](https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/files/7787867/data_understanding_and_preparation.1.pdf)

**Comment by tordans** [comment]
Hey everyone, @SupaplexOSM did an analysis last week. The data is now available at https://parkraum.osm-verkehrswende.org/posts/2022-07-15-einflussfaktoren-datenqualitaet. Thanks for all your input!
