### ISSUE TITLE
Create parking lane script

### ISSUE THREAD

**Issue by tordans** [SupaplexOSM/strassenraumkarte-neukoelln#6]
This issue tracks the progress to recreate the script from https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/tree/main/scripts/parking_lanes in a way that runs faster and allows daily (hourly) runs for an area like Berlin.

_TODO: Add todo :-)_

**Comment by SupaplexOSM** [comment]
See https://github.com/gislars/strassenraum-berlin for an follow-up project.
