### ISSUE TITLE
Create debug layer with additional info

### ISSUE THREAD

**Issue by tordans** [SupaplexOSM/strassenraumkarte-neukoelln#7]
The script at https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/tree/main/scripts/parking_lanes creates a raw output of results with debugging info. This view is ideal to explain the "subtractive parking lane calculation method" in the sense that is shows what is tagged on the lane (car-block next to the sane) and which parts are used to subtract from the result (circles).

This view will be an ideal companion when explaining the method and mapping a (new) region or adding details to a region.

**Current output:**

![image](https://user-images.githubusercontent.com/111561/151712803-fb0d7249-e5fc-41f6-96bf-9420435b73dc.png)

**This issue is meant to discuss and monitor the creating of a debug layer for general use**

# Generation

This is tracked in https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/issues/6

# Visualisation

- [ ] Visualize where there is data and where no data is missing
  **Goal:** Use the map to show areas that need mapping.

- [ ] Show where no parking is permitted (this might be the case already)?
  **Goal:** Show all the `parking:lane` tags in some way visually.

- [ ] Show count of parking spots next to the car-blocks – eg. [like zoom 18 does](https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=parkingmap#18/52.47932/13.44321).  <img src="https://user-images.githubusercontent.com/111561/151712850-881ddfb5-3729-4599-931b-f2b85eb340fc.png" height=80 />
  **Goal:** Have both, the illustrative blocks as well as the numbers in one view

- [ ] Write `check_date:parking:lane` next to the lane and an info when none given; maybe the update-at-date of the way-segment as a fallback?
  **Goal:** Start communicating this tag as the way to record up-to-dateness of the data. (SC and no other editor uses it ATM, so this might be for the future…)

- [ ] Write `conditional`s next to the lane if given
  **Goal:** Make this data visible.
   - Eg. "Nur zum Laden von E-Fahrzeugen zwischen 8 und 18 Uhr"
   - Maybe use a symbol system for this?
   - [x] ~~This does not belong here, but we should think about how to tag the fact, that no special conditions are present. Otherwise, we cannot track the progress of this dataset.~~ => That would be `parking:condition:<opt_side>=free` https://wiki.openstreetmap.org/wiki/Key:parking:condition

- [ ] Write the type of subtraction on the circle (or somewhere, TODO)
  **Goal:** Give visibility to which data we use to subtract, like "driveway", "crossing", "junction"
  - [ ] And add additional details like "default width 2m" or "width=3m" (if tagged)

**Comment by SupaplexOSM** [comment]
I will close this as this issue is outdated/not related to the strassenraumkarte map style. For documentation: meanwhile we have a follow up project at https://github.com/osmberlin/osm-parking-processing.
