### ISSUE TITLE
Usage for other towns/cites - How to generate all the geojson

### ISSUE THREAD

**Issue by MTRNord** [SupaplexOSM/strassenraumkarte-neukoelln#9]
Hi,

I had a look at this, and I am kinda wondering: How do I get from OSM to the files in the data folder? The scripts are, I am guessing, related but seem to not actually create the files. So I am assuming it is some manual step needed? Any hints on where to start for this? :)

**Comment by MTRNord** [comment]
To be more precisely word this: Which of the data is needed for the maps. As the data page itself seems highly specific to Berlin and likely is not available everywhere. :)

**Comment by MTRNord** [comment]
Actually closing as I guess this is explained in the readme. :(

**Comment by tordans** [comment]
@MTRNord you are right, it's not possible to setup the same map somewhere else at this time.

Supaplex030 is looking into sharing his Qgis styles and process in the future which would allow you to try to replicate the results in the same, manual-semi-automated way that it is done in Neukölln at the moment. But there is not timeline for that ATM.

We started writing ab post about it and about the effort it would take to setup the map in https://supaplexosm.github.io/strassenraumkarte-neukoelln/posts/2021-12-13-evaluate-tradeoffs-in-data-quality-vs-mapping-details but never finished the post (yet). In https://supaplexosm.github.io/strassenraumkarte-neukoelln/posts/2021-12-13-evaluate-tradeoffs-in-data-quality-vs-mapping-details#the-current-process we go into details about just the topic of parking lane tagging that is required to add the cars on the map. We are in the process of improving this part of the process to get it going for another district and maybe all Berlin.

I hope this map inspires you nonetheless to add more details to your neighbourhood :-).

**Comment by MTRNord** [comment]
Thanks for the links :) Thats great. And yeah I am currently starting to add details for my town :) Some of them make even osmAnd look nicer :D

**Comment by mikedld** [comment]
FYI I've created a small script that allowed me to generate a few maps for Portugal, should hopefully be suitable for other locations too with slight adjustments: https://github.com/mikedld/osm-strassenraumkarte-generator. If you find anything there of use, including changes in the submodules, feel free to pull from there or let me know you want PRs ;)
